-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 16:44:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdd_rfid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_rfid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_rfid` DEFAULT CHARACTER SET utf8 ;
USE `bdd_rfid` ;

-- -----------------------------------------------------
-- Table `bdd_rfid`.`tagrfid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rfid`.`tagrfid` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NomTag` VARCHAR(45) NULL,
  `article_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rfid`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rfid`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `disponible` TINYINT NULL,
  `marque` VARCHAR(45) NULL,
  `modele` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NULL,
  `qrcode` VARCHAR(45) NULL,
  `tagrfid_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_idx` (`tagrfid_id` ASC),
  CONSTRAINT `fk_tag`
    FOREIGN KEY (`tagrfid_id`)
    REFERENCES `bdd_rfid`.`tagrfid` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rfid`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rfid`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `fonction` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  `commentaires` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rfid`.`Identification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rfid`.`Identification` (
  `idIdentification` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `motdepasse` VARCHAR(45) NULL,
  PRIMARY KEY (`idIdentification`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rfid`.`emprunt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rfid`.`emprunt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `debut` DATETIME NULL,
  `fin` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idArticle_idx` (`article_id` ASC),
  INDEX `fk_utilisateur_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_idArticle`
    FOREIGN KEY (`article_id`)
    REFERENCES `bdd_rfid`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `bdd_rfid`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rfid`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rfid`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` DOUBLE NULL,
  `lattitude` DOUBLE NULL,
  `emprunt_id` INT NULL,
  `heure` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprunt_idx_idx` (`emprunt_id` ASC),
  CONSTRAINT `fk_emprunt_idx`
    FOREIGN KEY (`emprunt_id`)
    REFERENCES `bdd_rfid`.`emprunt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
