<?php

namespace SFL2\ApplicationBundle\Repository;

/**
 * EmpruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpruntRepository extends \Doctrine\ORM\EntityRepository
{
    //public function getEmpruntWithUtilisateur()
    //{
    //    $qb = $this->createQueryBuilder('nom')
    //               ->from('utilisateur', 'u')
    //               ->join('emprunt', 'emp');
    //               //->where('u.id = emp.id');
                
    
    //    return $qb
     //           ->getQuery()
    //            ->getResult();
    //}
}
